Add env specific config for housing repairs online api
Newarkandsherwood/housing-repairs-online pull request #8
Opened 2022-07-14 10:28 UTC by maysakanoni

2022-07-14 10:37 UTC, maysakanoni commented
![](https://github.trello.services/images/mini-trello-icon.png) [Allow differentiated configuration between staging and production for HousingRepairsOnlineApi](https://trello.com/c/OcUwkiwk/125-allow-differentiated-configuration-between-staging-and-production-for-housingrepairsonlineapi)

2022-07-18 09:02 UTC, Bhavesh-Patel requested changes
Couple of minor change requests

2022-07-18 09:02 UTC, Bhavesh-Patel commented on docs/adoption.md
> +| `INTERNAL_EMAIL_PRODUCTION`             | Internal email address for receiving repair request details, for any manual follow-on process in production  |
Update the environment text style for consistency with other changes.
```suggestion
| `INTERNAL_EMAIL_PRODUCTION`             | Internal email address for receiving repair request details, for any manual follow-on process in _Production_  |
```

2022-07-18 09:02 UTC, Bhavesh-Patel commented on docs/adoption.md
> +| `INTERNAL_EMAIL_STAGING`                | Internal email address for receiving repair request details, for any manual follow-on process in staging     |
Update the environment text style for consistency with other changes.
```suggestion
| `INTERNAL_EMAIL_STAGING`                | Internal email address for receiving repair request details, for any manual follow-on process in _Staging_     |
```

2022-07-19 08:09 UTC, Bhavesh-Patel approved these changes

2022-07-19 13:13 UTC, jamiejordanmt approved these changes

2022-07-19 14:34 UTC, merged